# Build settings
remote_theme: pages-themes/leap-day@v0.2.0
markdown: CommonMarkGhPages
plugins:
  - jekyll-timeago
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-relative-links
    
