# Build settings
title: "Jekyll Actions Demo"
### Built settings ###

url: "https://vanamsandeep.github.io"
baseurl: "/testrepo"

github_username: vanamsandeep
theme: minima
markdown: CommonMarkGhPages
plugins:
  - jekyll-timeago
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-relative-links
    
