# Build settings
title: "Jekyll Actions Demo with leap-day theme"
### Built settings ###

url: "https://vanamsandeep.github.io"
baseurl: "/testrepo"

github_username: vanamsandeep
remote_theme: pages-themes/leap-day@v0.2.0

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
pre-commit:
  - check: FrontMatterVariableExists
    variables: ['description', 'image']
  - check: FrontMatterVariableIsNotDuplicate
    variables: ['description']
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ['description', 'title']
  - check: NoDuplicateTags 
  
plugins:
  - jekyll-timeago
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-default-layout
    
